### ISSUE TITLE
Checklist de cosas que hay que hacer

### ISSUE THREAD

**Issue by davidglezz** [Arquisoft/Voting_3a#13]
Para que nadie se escaquee y diga que no sabia que hacer. Cada cual es libre para añadir nuevas tareas.

- Codigo
    - [x] Integrar esa parte nueva que me comentábais
    - [x] Arreglar Test
    - [x] Comprobar que cada subsistema funciona correctamente.
        - [x] Censuses
        - [x] Voters
        - [x] VoteCounting
        - [x] VotingSystem
    - [x] Terminar de implementar unas cosas de VoteCounting.
    - [x] Probar que ya se puede hacer la historia de usuario básica para un video demostrativo.

- Documentación
    - [x] Comprobar nombres de paquetes, ...

- Otros
    - [x] Video

**Comment by Vodkaneitor93** [comment]
Integrada parte restante de VotingSystem

**Comment by Vodkaneitor93** [comment]
VotingSystem funcional al fin
